### ISSUE TITLE
Station number seems rounded in show nearby station

### ISSUE THREAD

**Issue by avelo** [ocean-data-qc/ocean-data-qc#4]
Station number seems rounded in show nearby station, If I use 12 and 12.1 as station names, just two 12 different options seems to be shown.

Furthermore:
1.- Instead of just the number in plain text, a dropdown could be fitted there, so the user can pick an specific station, instead of having go through them all
2.- It would be nice to perform a sort in the stations

**Comment by chesucr** [comment]
Okay, I think could keep both behaviours, go to the next and previous station and select one from the dropdown

**Comment by ghost** [comment]
- [x] Keep station names. Done [here](https://github.com/ocean-data-qc/ocean-data-qc/commit/3f156d8a52d9cf33c0cec8ca11536f1340065f10)
- [x] Create a dropdown for stations. [Commit](https://github.com/ocean-data-qc/ocean-data-qc/commit/84232a7f7dc88ef57e8d023986d3d3457c4d90af)
- [x] Sort Stations. Same commit as the previous one

**Comment by ghost** [comment]
I had to apply [this fix](https://github.com/ocean-data-qc/ocean-data-qc/commit/3f6a03c8da66b33a312760d89c07288f2e6dd8c4) afterwards as well
