### ISSUE TITLE
Node modules deprecation

### ISSUE THREAD

**Issue by ghost** [ocean-data-qc/ocean-data-qc#6]
These deprecations showed up when I did `yarn install` in Linux

```
warning cross-zip@2.1.6: Possible security issue issue found in 2.x. Please update to 3.x
warning popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning request-promise > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning url-exists > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by chesucr** [comment]
Also upgrade `electron-builder` to make it work with MacOS:

![image](https://user-images.githubusercontent.com/11211829/75045074-eb856d00-54c2-11ea-9339-fdd269b567ad.png)

**Comment by chesucr** [comment]
* `electron-builder` updated to the 22.7.0 version
* `cross-zip` updated to the 3.1.0 version
* `url-exists` migrated to `url-exist`, this other one does not use the deprecated module `request`
* `popper.js` I need to keep the version to keep Bootstrap working
* `request-promise` module removed. Apparently, I don't really use it
